/*
 * HEATING_ELEMENT_LED.c
 *
 *  Author: Mostafa Ayman
 */ 

#include "HEATING_ELEMENT_LED.h"
#include "DIO.h"
void HEATING_ELEMENT_LED_INIT(void){
	PIN_MODE(HEATING_ELEMENT_LED_PIN,OUTPUT);
}
void HEATING_ELEMENT_LED_ON(void){
	PIN_WRITE(HEATING_ELEMENT_LED_PIN,HIGH);
}
void HEATING_ELEMENT_LED_OFF(void){
	PIN_WRITE(HEATING_ELEMENT_LED_PIN,LOW);
}
void HEATING_ELEMENT_LED_TOGGLE(void){
	PIN_TOGGLE(HEATING_ELEMENT_LED_PIN);
}