/*
 * S_SEG.c
 *
 *  Author: MOSTAFA AYMAN
 */ 
#include "S_SEG.h"

void S_SEG_INIT(){
	PIN_MODE(S_SEG_1_PIN_A,OUTPUT);
	PIN_MODE(S_SEG_1_PIN_B,OUTPUT);
	PIN_MODE(S_SEG_1_PIN_C,OUTPUT);
	PIN_MODE(S_SEG_1_PIN_D,OUTPUT);
	
	PIN_MODE(S_SEG_2_PIN_A,OUTPUT);
	PIN_MODE(S_SEG_2_PIN_B,OUTPUT);
	PIN_MODE(S_SEG_2_PIN_C,OUTPUT);
	PIN_MODE(S_SEG_2_PIN_D,OUTPUT);
	
	PIN_MODE(S_SEG_1_EN_PIN,OUTPUT);
	PIN_MODE(S_SEG_2_EN_PIN,OUTPUT);
}
void S_SEG_ON(void){
	PIN_WRITE(S_SEG_1_EN_PIN,HIGH);
	PIN_WRITE(S_SEG_2_EN_PIN,HIGH);
}
void S_SEG_OFF(void){
	PIN_WRITE(S_SEG_1_EN_PIN,LOW);
	PIN_WRITE(S_SEG_2_EN_PIN,LOW);
}
void S_SEG_TOGGLE(void){
	PIN_TOGGLE(S_SEG_1_EN_PIN);
	PIN_TOGGLE(S_SEG_2_EN_PIN);
}
void S_SEG_DISPLAY(uint8 num){
	
	uint8 num_1  = num%10;
	uint8 num_10 = num/10;
	switch(num_1){
		case 0:
		PIN_WRITE(S_SEG_1_PIN_A,LOW);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 1:
		PIN_WRITE(S_SEG_1_PIN_A,HIGH);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 2:
		PIN_WRITE(S_SEG_1_PIN_A,LOW);
		PIN_WRITE(S_SEG_1_PIN_B,HIGH);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 3:
		PIN_WRITE(S_SEG_1_PIN_A,HIGH);
		PIN_WRITE(S_SEG_1_PIN_B,HIGH);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 4:
		PIN_WRITE(S_SEG_1_PIN_A,LOW);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,HIGH);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 5:
		PIN_WRITE(S_SEG_1_PIN_A,HIGH);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,HIGH);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 6:
		PIN_WRITE(S_SEG_1_PIN_A,LOW);
		PIN_WRITE(S_SEG_1_PIN_B,HIGH);
		PIN_WRITE(S_SEG_1_PIN_C,HIGH);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 7:
		PIN_WRITE(S_SEG_1_PIN_A,HIGH);
		PIN_WRITE(S_SEG_1_PIN_B,HIGH);
		PIN_WRITE(S_SEG_1_PIN_C,HIGH);
		PIN_WRITE(S_SEG_1_PIN_D,LOW);
		break;
		case 8:
		PIN_WRITE(S_SEG_1_PIN_A,LOW);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,HIGH);
		break;
		case 9:
		PIN_WRITE(S_SEG_1_PIN_A,HIGH);
		PIN_WRITE(S_SEG_1_PIN_B,LOW);
		PIN_WRITE(S_SEG_1_PIN_C,LOW);
		PIN_WRITE(S_SEG_1_PIN_D,HIGH);
		break;
	}
	switch(num_10){
		case 0:
		PIN_WRITE(S_SEG_2_PIN_A,LOW);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 1:
		PIN_WRITE(S_SEG_2_PIN_A,HIGH);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 2:
		PIN_WRITE(S_SEG_2_PIN_A,LOW);
		PIN_WRITE(S_SEG_2_PIN_B,HIGH);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 3:
		PIN_WRITE(S_SEG_2_PIN_A,HIGH);
		PIN_WRITE(S_SEG_2_PIN_B,HIGH);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 4:
		PIN_WRITE(S_SEG_2_PIN_A,LOW);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,HIGH);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 5:
		PIN_WRITE(S_SEG_2_PIN_A,HIGH);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,HIGH);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 6:
		PIN_WRITE(S_SEG_2_PIN_A,LOW);
		PIN_WRITE(S_SEG_2_PIN_B,HIGH);
		PIN_WRITE(S_SEG_2_PIN_C,HIGH);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 7:
		PIN_WRITE(S_SEG_2_PIN_A,HIGH);
		PIN_WRITE(S_SEG_2_PIN_B,HIGH);
		PIN_WRITE(S_SEG_2_PIN_C,HIGH);
		PIN_WRITE(S_SEG_2_PIN_D,LOW);
		break;
		case 8:
		PIN_WRITE(S_SEG_2_PIN_A,LOW);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,HIGH);
		break;
		case 9:
		PIN_WRITE(S_SEG_2_PIN_A,HIGH);
		PIN_WRITE(S_SEG_2_PIN_B,LOW);
		PIN_WRITE(S_SEG_2_PIN_C,LOW);
		PIN_WRITE(S_SEG_2_PIN_D,HIGH);
		break;
	}
	}